// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmY0KpYsBx--tEfnoDtt7xZeIF3-mjVYE',
    appId: '1:809714617948:web:9ed5aebc94ad49e4606099',
    messagingSenderId: '809714617948',
    projectId: 'hedieaty-d79be',
    authDomain: 'hedieaty-d79be.firebaseapp.com',
    storageBucket: 'hedieaty-d79be.firebasestorage.app',
    measurementId: 'G-TX0XSXQMRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHK02nBB6cRHZ1-XkLr60F8MdS3lzwD2o',
    appId: '1:809714617948:android:c764e895ba63a000606099',
    messagingSenderId: '809714617948',
    projectId: 'hedieaty-d79be',
    storageBucket: 'hedieaty-d79be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEu4wuRcE7YAhT7LSRdDiRca2ESABiVDk',
    appId: '1:809714617948:ios:6e98ddb75f342e51606099',
    messagingSenderId: '809714617948',
    projectId: 'hedieaty-d79be',
    storageBucket: 'hedieaty-d79be.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEu4wuRcE7YAhT7LSRdDiRca2ESABiVDk',
    appId: '1:809714617948:ios:6e98ddb75f342e51606099',
    messagingSenderId: '809714617948',
    projectId: 'hedieaty-d79be',
    storageBucket: 'hedieaty-d79be.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmY0KpYsBx--tEfnoDtt7xZeIF3-mjVYE',
    appId: '1:809714617948:web:5e181bde4f45d4b9606099',
    messagingSenderId: '809714617948',
    projectId: 'hedieaty-d79be',
    authDomain: 'hedieaty-d79be.firebaseapp.com',
    storageBucket: 'hedieaty-d79be.firebasestorage.app',
    measurementId: 'G-H2YFHC94RC',
  );

}